export interface Country {
  name: string
  code: string
  flag: string
  iso: string
  shortCode: string
}

export const countries: Country[] = [
  { name: 'India', code: '+91', flag: '🇮🇳', iso: 'IN', shortCode: 'IND' },
  { name: 'United States', code: '+1', flag: '🇺🇸', iso: 'US', shortCode: 'USA' },
  { name: 'United Kingdom', code: '+44', flag: '🇬🇧', iso: 'GB', shortCode: 'UK' },
  { name: 'United Arab Emirates', code: '+971', flag: '🇦🇪', iso: 'AE', shortCode: 'UAE' },
  { name: 'Canada', code: '+1', flag: '🇨🇦', iso: 'CA', shortCode: 'CAN' },
  { name: 'Australia', code: '+61', flag: '🇦🇺', iso: 'AU', shortCode: 'AUS' },
  { name: 'Singapore', code: '+65', flag: '🇸🇬', iso: 'SG', shortCode: 'SGP' },
  { name: 'Germany', code: '+49', flag: '🇩🇪', iso: 'DE', shortCode: 'GER' },
  { name: 'France', code: '+33', flag: '🇫🇷', iso: 'FR', shortCode: 'FRA' },
  { name: 'Japan', code: '+81', flag: '🇯🇵', iso: 'JP', shortCode: 'JPN' },
  { name: 'Saudi Arabia', code: '+966', flag: '🇸🇦', iso: 'SA', shortCode: 'KSA' },
  { name: 'Qatar', code: '+974', flag: '🇶🇦', iso: 'QA', shortCode: 'QAT' },
  { name: 'Kuwait', code: '+965', flag: '🇰🇼', iso: 'KW', shortCode: 'KWT' },
  { name: 'Oman', code: '+968', flag: '🇴🇲', iso: 'OM', shortCode: 'OMN' },
  { name: 'Bahrain', code: '+973', flag: '🇧🇭', iso: 'BH', shortCode: 'BHR' },
  { name: 'Afghanistan', code: '+93', flag: '🇦🇫', iso: 'AF', shortCode: 'AFG' },
  { name: 'Albania', code: '+355', flag: '🇦🇱', iso: 'AL', shortCode: 'ALB' },
  { name: 'Algeria', code: '+213', flag: '🇩🇿', iso: 'DZ', shortCode: 'ALG' },
  { name: 'Andorra', code: '+376', flag: '🇦🇩', iso: 'AD', shortCode: 'AND' },
  { name: 'Angola', code: '+244', flag: '🇦🇴', iso: 'AO', shortCode: 'ANG' },
  { name: 'Antigua and Barbuda', code: '+1-268', flag: '🇦🇬', iso: 'AG', shortCode: 'ATG' },
  { name: 'Argentina', code: '+54', flag: '🇦🇷', iso: 'AR', shortCode: 'ARG' },
  { name: 'Armenia', code: '+374', flag: '🇦🇲', iso: 'AM', shortCode: 'ARM' },
  { name: 'Austria', code: '+43', flag: '🇦🇹', iso: 'AT', shortCode: 'AUT' },
  { name: 'Azerbaijan', code: '+994', flag: '🇦🇿', iso: 'AZ', shortCode: 'AZE' },
  { name: 'Bahamas', code: '+1-242', flag: '🇧🇸', iso: 'BS', shortCode: 'BHS' },
  { name: 'Bangladesh', code: '+880', flag: '🇧🇩', iso: 'BD', shortCode: 'BAN' },
  { name: 'Barbados', code: '+1-246', flag: '🇧🇧', iso: 'BB', shortCode: 'BRB' },
  { name: 'Belarus', code: '+375', flag: '🇧🇾', iso: 'BY', shortCode: 'BLR' },
  { name: 'Belgium', code: '+32', flag: '🇧🇪', iso: 'BE', shortCode: 'BEL' },
  { name: 'Belize', code: '+501', flag: '🇧ℤ', iso: 'BZ', shortCode: 'BLZ' },
  { name: 'Benin', code: '+229', flag: '🇧🇯', iso: 'BJ', shortCode: 'BEN' },
  { name: 'Bhutan', code: '+975', flag: '🇧🇹', iso: 'BT', shortCode: 'BHU' },
  { name: 'Bolivia', code: '+591', flag: '🇧🇴', iso: 'BO', shortCode: 'BOL' },
  { name: 'Bosnia and Herzegovina', code: '+387', flag: '🇧🇦', iso: 'BA', shortCode: 'BIH' },
  { name: 'Botswana', code: '+267', flag: '🇧🇼', iso: 'BW', shortCode: 'BOT' },
  { name: 'Brazil', code: '+55', flag: '🇧🇷', iso: 'BR', shortCode: 'BRA' },
  { name: 'Brunei', code: '+673', flag: '🇧🇳', iso: 'BN', shortCode: 'BRN' },
  { name: 'Bulgaria', code: '+359', flag: '🇧🇬', iso: 'BG', shortCode: 'BUL' },
  { name: 'Burkina Faso', code: '+226', flag: '🇧🇫', iso: 'BF', shortCode: 'BUR' },
  { name: 'Burundi', code: '+257', flag: '🇧🇮', iso: 'BI', shortCode: 'BDI' },
  { name: 'Cambodia', code: '+855', flag: '🇰🇭', iso: 'KH', shortCode: 'CAM' },
  { name: 'Cameroon', code: '+237', flag: '🇨🇲', iso: 'CM', shortCode: 'CMR' },
  { name: 'Cape Verde', code: '+238', flag: '🇨🇻', iso: 'CV', shortCode: 'CPV' },
  { name: 'Central African Republic', code: '+236', flag: '🇨🇫', iso: 'CF', shortCode: 'CAF' },
  { name: 'Chad', code: '+235', flag: '🇹🇩', iso: 'TD', shortCode: 'CHA' },
  { name: 'Chile', code: '+56', flag: '🇨🇱', iso: 'CL', shortCode: 'CHI' },
  { name: 'China', code: '+86', flag: '🇨🇳', iso: 'CN', shortCode: 'CHN' },
  { name: 'Colombia', code: '+57', flag: '🇨🇴', iso: 'CO', shortCode: 'COL' },
  { name: 'Comoros', code: '+269', flag: '🇰🇲', iso: 'KM', shortCode: 'COM' },
  { name: 'Congo', code: '+242', flag: '🇨🇬', iso: 'CG', shortCode: 'COG' },
  { name: 'Congo (DRC)', code: '+243', flag: '🇨🇩', iso: 'CD', shortCode: 'COD' },
  { name: 'Costa Rica', code: '+506', flag: '🇨🇷', iso: 'CR', shortCode: 'CRC' },
  { name: 'Croatia', code: '+385', flag: '🇭🇷', iso: 'HR', shortCode: 'CRO' },
  { name: 'Cuba', code: '+53', flag: '🇨🇺', iso: 'CU', shortCode: 'CUB' },
  { name: 'Cyprus', code: '+357', flag: '🇨🇾', iso: 'CY', shortCode: 'CYP' },
  { name: 'Czech Republic', code: '+420', flag: '🇨🇿', iso: 'CZ', shortCode: 'CZE' },
  { name: 'Denmark', code: '+45', flag: '🇩🇰', iso: 'DK', shortCode: 'DEN' },
  { name: 'Djibouti', code: '+253', flag: '🇩🇯', iso: 'DJ', shortCode: 'DJI' },
  { name: 'Dominica', code: '+1-767', flag: '🇩🇲', iso: 'DM', shortCode: 'DMA' },
  { name: 'Dominican Republic', code: '+1-809', flag: '🇩🇴', iso: 'DO', shortCode: 'DOM' },
  { name: 'Ecuador', code: '+593', flag: '🇪🇨', iso: 'EC', shortCode: 'ECU' },
  { name: 'Egypt', code: '+20', flag: '🇪🇬', iso: 'EG', shortCode: 'EGY' },
  { name: 'El Salvador', code: '+503', flag: '🇸🇻', iso: 'SV', shortCode: 'SLV' },
  { name: 'Equatorial Guinea', code: '+240', flag: '🇬🇶', iso: 'GQ', shortCode: 'EQG' },
  { name: 'Eritrea', code: '+291', flag: '🇪🇷', iso: 'ER', shortCode: 'ERI' },
  { name: 'Estonia', code: '+372', flag: '🇪🇪', iso: 'EE', shortCode: 'EST' },
  { name: 'Eswatini', code: '+268', flag: '🇸🇿', iso: 'SZ', shortCode: 'SWZ' },
  { name: 'Ethiopia', code: '+251', flag: '🇪🇹', iso: 'ET', shortCode: 'ETH' },
  { name: 'Fiji', code: '+679', flag: '🇫🇯', iso: 'FJ', shortCode: 'FIJ' },
  { name: 'Finland', code: '+358', flag: '🇫🇮', iso: 'FI', shortCode: 'FIN' },
  { name: 'Gabon', code: '+241', flag: '🇬🇦', iso: 'GA', shortCode: 'GAB' },
  { name: 'Gambia', code: '+220', flag: '🇬🇲', iso: 'GM', shortCode: 'GAM' },
  { name: 'Georgia', code: '+995', flag: '🇬🇪', iso: 'GE', shortCode: 'GEO' },
  { name: 'Ghana', code: '+233', flag: '🇬🇭', iso: 'GH', shortCode: 'GHA' },
  { name: 'Greece', code: '+30', flag: '🇬🇷', iso: 'GR', shortCode: 'GRE' },
  { name: 'Grenada', code: '+1-473', flag: '🇬🇩', iso: 'GD', shortCode: 'GRN' },
  { name: 'Guatemala', code: '+502', flag: '🇬🇹', iso: 'GT', shortCode: 'GUA' },
  { name: 'Guinea', code: '+224', flag: '🇬🇳', iso: 'GN', shortCode: 'GUI' },
  { name: 'Guinea-Bissau', code: '+245', flag: '🇬🇼', iso: 'GW', shortCode: 'GBS' },
  { name: 'Guyana', code: '+592', flag: '🇬🇾', iso: 'GY', shortCode: 'GUY' },
  { name: 'Haiti', code: '+509', flag: '🇭🇹', iso: 'HT', shortCode: 'HAI' },
  { name: 'Honduras', code: '+504', flag: '🇭🇳', iso: 'HN', shortCode: 'HON' },
  { name: 'Hong Kong', code: '+852', flag: '🇭🇰', iso: 'HK', shortCode: 'HKG' },
  { name: 'Hungary', code: '+36', flag: '🇭🇺', iso: 'HU', shortCode: 'HUN' },
  { name: 'Iceland', code: '+354', flag: '🇮🇸', iso: 'IS', shortCode: 'ISL' },
  { name: 'Indonesia', code: '+62', flag: '🇮🇩', iso: 'ID', shortCode: 'INA' },
  { name: 'Iran', code: '+98', flag: '🇮🇷', iso: 'IR', shortCode: 'IRI' },
  { name: 'Iraq', code: '+964', flag: '🇮🇶', iso: 'IQ', shortCode: 'IRQ' },
  { name: 'Ireland', code: '+353', flag: '🇮🇪', iso: 'IE', shortCode: 'IRL' },
  { name: 'Israel', code: '+972', flag: '🇮🇱', iso: 'IL', shortCode: 'ISR' },
  { name: 'Italy', code: '+39', flag: '🇮🇹', iso: 'IT', shortCode: 'ITA' },
  { name: 'Ivory Coast', code: '+225', flag: '🇨🇮', iso: 'CI', shortCode: 'CIV' },
  { name: 'Jamaica', code: '+1-876', flag: '🇯🇲', iso: 'JM', shortCode: 'JAM' },
  { name: 'Jordan', code: '+962', flag: '🇯🇴', iso: 'JO', shortCode: 'JOR' },
  { name: 'Kazakhstan', code: '+7', flag: '🇰🇿', iso: 'KZ', shortCode: 'KAZ' },
  { name: 'Kenya', code: '+254', flag: '🇰🇪', iso: 'KE', shortCode: 'KEN' },
  { name: 'Kiribati', code: '+686', flag: '🇰🇮', iso: 'KI', shortCode: 'KIR' },
  { name: 'Kosovo', code: '+383', flag: '🇽🇰', iso: 'XK', shortCode: 'KOS' },
  { name: 'Kyrgyzstan', code: '+996', flag: '🇰🇬', iso: 'KG', shortCode: 'KGZ' },
  { name: 'Laos', code: '+856', flag: '🇱🇦', iso: 'LA', shortCode: 'LAO' },
  { name: 'Latvia', code: '+371', flag: '🇱🇻', iso: 'LV', shortCode: 'LAT' },
  { name: 'Lebanon', code: '+961', flag: '🇱🇧', iso: 'LB', shortCode: 'LBN' },
  { name: 'Lesotho', code: '+266', flag: '🇱🇸', iso: 'LS', shortCode: 'LES' },
  { name: 'Liberia', code: '+231', flag: '🇱🇷', iso: 'LR', shortCode: 'LBR' },
  { name: 'Libya', code: '+218', flag: '🇱🇾', iso: 'LY', shortCode: 'LBY' },
  { name: 'Liechtenstein', code: '+423', flag: '🇱🇮', iso: 'LI', shortCode: 'LIE' },
  { name: 'Lithuania', code: '+370', flag: '🇱🇹', iso: 'LT', shortCode: 'LTU' },
  { name: 'Luxembourg', code: '+352', flag: '🇱🇺', iso: 'LU', shortCode: 'LUX' },
  { name: 'Macau', code: '+853', flag: '🇲🇴', iso: 'MO', shortCode: 'MAC' },
  { name: 'Madagascar', code: '+261', flag: '🇲🇬', iso: 'MG', shortCode: 'MAD' },
  { name: 'Malawi', code: '+265', flag: '🇲🇼', iso: 'MW', shortCode: 'MAW' },
  { name: 'Malaysia', code: '+60', flag: '🇲🇾', iso: 'MY', shortCode: 'MAS' },
  { name: 'Maldives', code: '+960', flag: '🇲🇻', iso: 'MV', shortCode: 'MDV' },
  { name: 'Mali', code: '+223', flag: '🇲🇱', iso: 'ML', shortCode: 'MLI' },
  { name: 'Malta', code: '+356', flag: '🇲🇹', iso: 'MT', shortCode: 'MLT' },
  { name: 'Marshall Islands', code: '+692', flag: '🇲🇭', iso: 'MH', shortCode: 'MHL' },
  { name: 'Mauritania', code: '+222', flag: '🇲🇷', iso: 'MR', shortCode: 'MTN' },
  { name: 'Mauritius', code: '+230', flag: '🇲🇺', iso: 'MU', shortCode: 'MRI' },
  { name: 'Mexico', code: '+52', flag: '🇲🇽', iso: 'MX', shortCode: 'MEX' },
  { name: 'Micronesia', code: '+691', flag: '🇫🇲', iso: 'FM', shortCode: 'FSM' },
  { name: 'Moldova', code: '+373', flag: '🇲🇩', iso: 'MD', shortCode: 'MDA' },
  { name: 'Monaco', code: '+377', flag: '🇲🇨', iso: 'MC', shortCode: 'MON' },
  { name: 'Mongolia', code: '+976', flag: '🇲🇳', iso: 'MN', shortCode: 'MGL' },
  { name: 'Montenegro', code: '+382', flag: '🇲🇪', iso: 'ME', shortCode: 'MNE' },
  { name: 'Morocco', code: '+212', flag: '🇲🇦', iso: 'MA', shortCode: 'MAR' },
  { name: 'Mozambique', code: '+258', flag: '🇲🇿', iso: 'MZ', shortCode: 'MOZ' },
  { name: 'Myanmar', code: '+95', flag: '🇲🇲', iso: 'MM', shortCode: 'MYA' },
  { name: 'Namibia', code: '+264', flag: '🇳🇦', iso: 'NA', shortCode: 'NAM' },
  { name: 'Nauru', code: '+674', flag: '🇳🇷', iso: 'NR', shortCode: 'NRU' },
  { name: 'Nepal', code: '+977', flag: '🇳🇵', iso: 'NP', shortCode: 'NEP' },
  { name: 'Netherlands', code: '+31', flag: '🇳🇱', iso: 'NL', shortCode: 'NED' },
  { name: 'New Zealand', code: '+64', flag: '🇳🇿', iso: 'NZ', shortCode: 'NZL' },
  { name: 'Nicaragua', code: '+505', flag: '🇳🇮', iso: 'NI', shortCode: 'NCA' },
  { name: 'Niger', code: '+227', flag: '🇳🇪', iso: 'NE', shortCode: 'NIG' },
  { name: 'Nigeria', code: '+234', flag: '🇳🇬', iso: 'NG', shortCode: 'NGR' },
  { name: 'North Korea', code: '+850', flag: '🇰🇵', iso: 'KP', shortCode: 'PRK' },
  { name: 'North Macedonia', code: '+389', flag: '🇲🇰', iso: 'MK', shortCode: 'MKD' },
  { name: 'Norway', code: '+47', flag: '🇳🇴', iso: 'NO', shortCode: 'NOR' },
  { name: 'Pakistan', code: '+92', flag: '🇵🇰', iso: 'PK', shortCode: 'PAK' },
  { name: 'Palau', code: '+680', flag: '🇵🇼', iso: 'PW', shortCode: 'PLW' },
  { name: 'Palestine', code: '+970', flag: '🇵🇸', iso: 'PS', shortCode: 'PLE' },
  { name: 'Panama', code: '+507', flag: '🇵🇦', iso: 'PA', shortCode: 'PAN' },
  { name: 'Papua New Guinea', code: '+675', flag: '🇵🇬', iso: 'PG', shortCode: 'PNG' },
  { name: 'Paraguay', code: '+595', flag: '🇵🇾', iso: 'PY', shortCode: 'PAR' },
  { name: 'Peru', code: '+51', flag: '🇵🇪', iso: 'PE', shortCode: 'PER' },
  { name: 'Philippines', code: '+63', flag: '🇵🇭', iso: 'PH', shortCode: 'PHI' },
  { name: 'Poland', code: '+48', flag: '🇵🇱', iso: 'PL', shortCode: 'POL' },
  { name: 'Portugal', code: '+351', flag: '🇵🇹', iso: 'PT', shortCode: 'POR' },
  { name: 'Romania', code: '+40', flag: '🇷🇴', iso: 'RO', shortCode: 'ROU' },
  { name: 'Russia', code: '+7', flag: '🇷🇺', iso: 'RU', shortCode: 'RUS' },
  { name: 'Rwanda', code: '+250', flag: '🇷🇼', iso: 'RW', shortCode: 'RWA' },
  { name: 'Saint Kitts and Nevis', code: '+1-869', flag: '🇰🇳', iso: 'KN', shortCode: 'SKN' },
  { name: 'Saint Lucia', code: '+1-758', flag: '🇱🇨', iso: 'LC', shortCode: 'LCA' },
  { name: 'Saint Vincent and Grenadines', code: '+1-784', flag: '🇻🇨', iso: 'VC', shortCode: 'VIN' },
  { name: 'Samoa', code: '+685', flag: '🇼🇸', iso: 'WS', shortCode: 'SAM' },
  { name: 'San Marino', code: '+378', flag: '🇸🇲', iso: 'SM', shortCode: 'SMR' },
  { name: 'Sao Tome and Principe', code: '+239', flag: '🇸🇹', iso: 'ST', shortCode: 'STP' },
  { name: 'Senegal', code: '+221', flag: '🇸🇳', iso: 'SN', shortCode: 'SEN' },
  { name: 'Serbia', code: '+381', flag: '🇷🇸', iso: 'RS', shortCode: 'SRB' },
  { name: 'Seychelles', code: '+248', flag: '🇸🇨', iso: 'SC', shortCode: 'SEY' },
  { name: 'Sierra Leone', code: '+232', flag: '🇸🇱', iso: 'SL', shortCode: 'SLE' },
  { name: 'Slovakia', code: '+421', flag: '🇸🇰', iso: 'SK', shortCode: 'SVK' },
  { name: 'Slovenia', code: '+386', flag: '🇸🇮', iso: 'SI', shortCode: 'SVN' },
  { name: 'Solomon Islands', code: '+677', flag: '🇸🇧', iso: 'SB', shortCode: 'SOL' },
  { name: 'Somalia', code: '+252', flag: '🇸🇴', iso: 'SO', shortCode: 'SOM' },
  { name: 'South Africa', code: '+27', flag: '🇿🇦', iso: 'ZA', shortCode: 'RSA' },
  { name: 'South Korea', code: '+82', flag: '🇰🇷', iso: 'KR', shortCode: 'KOR' },
  { name: 'South Sudan', code: '+211', flag: '🇸🇸', iso: 'SS', shortCode: 'SSD' },
  { name: 'Spain', code: '+34', flag: '🇪🇸', iso: 'ES', shortCode: 'ESP' },
  { name: 'Sri Lanka', code: '+94', flag: '🇱🇰', iso: 'LK', shortCode: 'SRI' },
  { name: 'Sudan', code: '+249', flag: '🇸🇩', iso: 'SD', shortCode: 'SUD' },
  { name: 'Suriname', code: '+597', flag: '🇸🇷', iso: 'SR', shortCode: 'SUR' },
  { name: 'Sweden', code: '+46', flag: '🇸🇪', iso: 'SE', shortCode: 'SWE' },
  { name: 'Switzerland', code: '+41', flag: '🇨🇭', iso: 'CH', shortCode: 'SUI' },
  { name: 'Syria', code: '+963', flag: '🇸🇾', iso: 'SY', shortCode: 'SYR' },
  { name: 'Taiwan', code: '+886', flag: '🇹🇼', iso: 'TW', shortCode: 'TWN' },
  { name: 'Tajikistan', code: '+992', flag: '🇹🇯', iso: 'TJ', shortCode: 'TJK' },
  { name: 'Tanzania', code: '+255', flag: '🇹🇿', iso: 'TZ', shortCode: 'TAN' },
  { name: 'Thailand', code: '+66', flag: '🇹🇭', iso: 'TH', shortCode: 'THA' },
  { name: 'Timor-Leste', code: '+670', flag: '🇹🇱', iso: 'TL', shortCode: 'TLS' },
  { name: 'Togo', code: '+228', flag: '🇹🇬', iso: 'TG', shortCode: 'TOG' },
  { name: 'Tonga', code: '+676', flag: '🇹🇴', iso: 'TO', shortCode: 'TGA' },
  { name: 'Trinidad and Tobago', code: '+1-868', flag: '🇹🇹', iso: 'TT', shortCode: 'TRI' },
  { name: 'Tunisia', code: '+216', flag: '🇹🇳', iso: 'TN', shortCode: 'TUN' },
  { name: 'Turkey', code: '+90', flag: '🇹🇷', iso: 'TR', shortCode: 'TUR' },
  { name: 'Turkmenistan', code: '+993', flag: '🇹🇲', iso: 'TM', shortCode: 'TKM' },
  { name: 'Tuvalu', code: '+688', flag: '🇹🇻', iso: 'TV', shortCode: 'TUV' },
  { name: 'Uganda', code: '+256', flag: '🇺🇬', iso: 'UG', shortCode: 'UGA' },
  { name: 'Ukraine', code: '+380', flag: '🇺🇦', iso: 'UA', shortCode: 'UKR' },
  { name: 'Uruguay', code: '+598', flag: '🇺🇾', iso: 'UY', shortCode: 'URU' },
  { name: 'Uzbekistan', code: '+998', flag: '🇺🇿', iso: 'UZ', shortCode: 'UZB' },
  { name: 'Vanuatu', code: '+678', flag: '🇻🇺', iso: 'VU', shortCode: 'VAN' },
  { name: 'Vatican City', code: '+379', flag: '🇻🇦', iso: 'VA', shortCode: 'VAT' },
  { name: 'Venezuela', code: '+58', flag: '🇻🇪', iso: 'VE', shortCode: 'VEN' },
  { name: 'Vietnam', code: '+84', flag: '🇻🇳', iso: 'VN', shortCode: 'VIE' },
  { name: 'Yemen', code: '+967', flag: '🇾🇪', iso: 'YE', shortCode: 'YEM' },
  { name: 'Zambia', code: '+260', flag: '🇿🇲', iso: 'ZM', shortCode: 'ZAM' },
  { name: 'Zimbabwe', code: '+263', flag: '🇿🇼', iso: 'ZW', shortCode: 'ZIM' },
]
